language: java
jdk:
  - oraclejdk8

sudo: false

env:
  - GROUP=index-sun
  - GROUP=index-com
  - GROUP=index-javax
  - GROUP=index-java
  - GROUP=index-jdk-org

script:  ./.travis-build.sh $GROUP

git:
  depth: 3
